### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [id347627/KottansHomeWork#2]
Given the number "3434343434343433" (16 digits)
Expected result: "Unknown" vendor, invalid number (15 digits allowed for American Express)
Actual result: "American Express"

**Comment by id347627** [comment]
added card number length verification.
the number "3434343434343433" is not recognized any more.
Actual result is "Unknown"  for this number.

Thanks, for reviewing my piece of "cake")

**Comment by intrueder** [comment]
Still reproducable for `"50000000000006114"` (17 digits)
Expected result: "Unknown" vendor
Actual result: "Maestro"

**Comment by id347627** [comment]
Please review http://www.mastercard.com/de/haendler/_globalAssets/pdf/ORME-Entire_Manual.pdf
 page # 111.
please find the short quote from that doc: 
"The Primary Account Number (PAN) must be no less than twelve (12) and no more than nineteen (19)
digits in length. All digits of the PAN must be numeric."

i believe we  should expect to see "Maestro" for the given number "50000000000006114"

**Comment by intrueder** [comment]
Sorry, root cause here is not 17 digits, but invalid number itself.

**Comment by id347627** [comment]
added verification of card number to the GetCreditCardVendor method.
it returns "Unknown"  for "50000000000006114" now

Thanks
