### ISSUE TITLE
Small issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [id347627/KottansHomeWork#3]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
I think, that such number should not pass validation, but it passes.

**Comment by id347627** [comment]
Fixed logic error in
https://github.com/id347627/KottansHomeWork/blob/master/main.cs#L90

**Comment by id347627** [comment]
it should not pass because vendor has been recognized as Uknown?

**Comment by id347627** [comment]
3 5 3 0 1 1 1 3 3 3 3 0 0 0 0 0 1
sum of the odd digits (starting from most right):
1 + 0 + 0 + 3 + 3 + 1 + 1 + 3 + 3 = 15;
sum of the even digits (starting from most right):
0+0+0+(3x2)+(3x2)+(1x2)+ 0 +(5x2-9) = 15;
total sum is 30
so this number should pass validation

**Comment by id347627** [comment]
3 5 3 0 1 1 1 3 3 3 3 0 0 0 0 0
sum of the odd digits (starting from most right):
0+0+0+3+3+1+0+5 = 12;
sum of the even digits (starting from most right):
0 + 0 + 3x2 + 3x2 + 1x2 + 1x2 + 3x2 + 3x2 = 28;
total sum is 40
so this number also should pass validation

**Comment by intrueder** [comment]
I agree, that this _**digit series**_ is valid according to Luhn, but the challenge is to validate _**credit card number**_. And such digits series can't be card number according to length restriction for JCB

**Comment by id347627** [comment]
this digit series (35301113333000001) will not pass validation now.
